# Generated by Django 5.0.3 on 2024-03-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apodos', models.CharField(max_length=60)),
                ('socios', models.IntegerField()),
                ('division', models.CharField(max_length=60)),
                ('fundacion', models.DateField()),
                ('colores_principales', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('nombre_fant', models.CharField(max_length=60)),
                ('capacidad', models.IntegerField()),
                ('ubicacion', models.IntegerField()),
                ('club', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('alias', models.CharField(max_length=60)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('nacionalidad', models.CharField(max_length=60)),
                ('esta_retirado', models.BooleanField()),
                ('goles', models.IntegerField()),
                ('asistencias', models.IntegerField()),
                ('cant_partidos', models.IntegerField()),
            ],
        ),
    ]
