# Generated by Django 5.0.3 on 2024-03-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega3Trueba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='partidos_empatados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='partidos_ganados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='partidos_perdidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='alias',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
