# Generated by Django 5.0.3 on 2024-03-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega3Trueba', '0002_jugador_imagen_jugador_partidos_empatados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='palmares',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(default=0, max_length=60),
        ),
    ]
