# Generated by Django 5.0.3 on 2024-03-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega3Trueba', '0003_jugador_palmares_jugador_posicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='estadio',
            name='ubicacion',
            field=models.CharField(max_length=60),
        ),
    ]
